---
swagger: '2.0'
info:
  version: 1.0.0
  title: Hello Service
paths:
  /hello:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: example query parameter
      operationId: getHello
      responses:
        200:
          description: responds with a Hello too
          schema:
              type: string
              description: returns with a string response
